### ISSUE TITLE
HTML output example is WRONG

### ISSUE THREAD

**Issue by arnoud999** [WillemSleegers/r-projects#1]
I'M REALLY ANGRY ABOUT THIS!

**Comment by WillemSleegers** [comment]
MY APOLOGIES, HULK ARNOUD. HTML OUTPUT IS NOW CORRECT! ALSO, CAPS ARE GREAT.

**Comment by arnoud999** [comment]
THANK YOU. I AM STILL ANGRY ABOUT A LOT OF THINGS BUT THIS IS NOT ONE OF THEM.
